#!/bin/bash

#region Constantes
URL_MIRRORLIST="https://www.archlinux.org/mirrorlist/?country=all&protocol=http&protocol=https&ip_version=4"
FILE="/tmp/mirrorlist.txt"
PING_COUNT=5
ERASE="\e[K"
#endregion

#region Colores
CLR_ROJO="\e[91m"
CLR_VERD="\e[92m"
CLR_AMAR="\e[93m"
CLR_FIN="\e[m"
#endregion

#region Funciones
_error() {
    if [ "$2" ]; then
        echo -e "${ERASE}${CLR_ROJO}check-mirrors: $2${CLR_FIN}" >&2
    fi
    exit $1
}

main() {
    obtener_lista || _error 1 "no se pudo obtener la lista de mirrors"
    procesar_lista
}

obtener_lista() {
    local cols=$(tput cols)
    local pad=31
    local size=$(($cols - $pad))
    echo -en "Obteniendo lista de mirrors ${CLR_AMAR}${URL_MIRRORLIST:0:$size}${CLR_FIN}...\r"

    wget "$URL_MIRRORLIST" -O "$FILE" > /dev/null 2>&1
}

procesar_lista() {
    local min_avg=400
    local min_url=

    local urls=$(cat $FILE | awk -F '/' '$1 ~ /Server/ { print $3 }')

    for url in $urls; do
        printf "${ERASE}Pingeando ${CLR_AMAR}%s${CLR_FIN}...\r" "$url"
        local avg_time=$(ping -c $PING_COUNT $url | tail -1 | awk -F '/' '{ print $5 }')
        if [ $avg_time ]; then
            if [ $(echo "$avg_time < $min_avg" | bc -l) -eq 1 ]; then
                min_avg=$avg_time
                min_url=$url
            fi
        fi
        sleep 1
    done

    _success "Mejor mirror" "$min_url"
    _success "Tiempo" "$min_avg"
}

_success() {
    printf "${ERASE}%s: ${CLR_VERD}%s${CLR_FIN}\n" "$1" "$2"
}
#endregion

main "$@"
