#!/bin/sh

error() {
    echo "\033[91m$@\033[m" >&2
    exit 1
}

[ ! -d ".git" ] && error "No es un repositorio de git"

url=$(git remote get-url origin)
servidor=$(echo $url | grep -Po '[^/@]*\.com')
repo=$(echo $url | grep -Po '[^/@]*\.com.*')

if [ $servidor = "gitlab.com" ]; then
    [ ! "$1" ] && error "No se ingresó el nombre del token para Gitlab"
    tokenName="$1:"
fi

# Read token
stty -echo
printf "Token: "
read token
stty echo
echo

[ ! $token ] && error "No se ingresó el token"

origin_url="https://$tokenName$token@$repo"

git remote set-url origin "$origin_url"
