#!/bin/bash

#region Colores
CLR_VERD="\e[92m"
CLR_AMAR="\e[93m"
CLR_ROSA="\e[95m"
CLR_CYAN="\e[96m"
CLR_FIN="\e[m"
#endregion

#region Constantes
ERASE="\e[K"
#endregion

if [[ $1 ]]; then
    if [[ $2 ]]; then
        echo -en "${ERASE}${CLR_AMAR}$1${CLR_FIN} = [${CLR_VERD}"
        shift
        echo -e "$@${CLR_FIN}]"
    else
        echo -e "${ERASE}${CLR_ROSA}$1${CLR_FIN}"
    fi
else
    echo -e "${ERASE}${CLR_CYAN}CHECKPOINT${CLR_FIN}"
fi

