#!/bin/bash

#region Constantes
FILE="$HOME/Baul/prueba.txt"
#endregion


main() {
    lista=$(obtener_lista)
    lista=$(filtrar_arch_linux $lista)

    for pkg in $lista; do
        actualizar_paquete $pkg
    done
}

obtener_lista() {
    # Obtiene la lista de paquetes desactualizados de Python.
    # Hay que quitar las dos primeras líneas, que son del encabezado.
    # pip list --outdated | awk '
    cat $FILE | tail -n +3 | awk '{ print $1 }'
}

filtrar_arch_linux() {
    # Filtra los paquetes instalados por paquetes de Arch Linux
    for pkg in $lista; do
        qs=$(pacman -Qqs $pkg)
        if [ ! "$qs" ]; then
            echo $pkg
        fi
    done
}

actualizar_paquete() {
    log pkg $pkg
    pip install $pkg -qU
}

main "$@"

