#!/bin/bash

main() {
    local dir=$(parsear_directorio "$@")

    if [ -z "$dir" ]; then
        _error 1 "no existe el directorio $dir"
    fi

    if [ -z "$(ls -A $dir 2> /dev/null )" ]; then
        _error 2 "el directorio está vacío"
    fi

    mostrar_subdirectorios "$dir"
}

_error() {
    if [ "$2" ]; then
        echo -e "\e[91msubdir: $2\e[m" >&2
    fi
    exit $1
}

parsear_directorio() {
    # Si no se especifica, se procesa el directorio actual.
    if [[ -z $1 ]]; then
        echo '*'
    else
        if [ -d $1 ]; then
            echo $1/'*'
        fi
    fi
}

mostrar_subdirectorios() {
    du -chs $dir | sort -h | awk '
        BEGIN {
            CLR_TOTAL = "\033[41m";
            CLR_GIGAS = "\033[91m";
            CLR_SIZE  = "\033[93m";
            CLR_END   = "\033[m";
        }
        $1 !~ /G/ {
            COLOR = CLR_SIZE
        }
        $1  ~ /G/ {
            COLOR = CLR_GIGAS
        }
        $2 !~ /^total$/ {
            # Primero imprimo el tamaño y después imprimo el nombre completo
            # con espacios.
            printf "%s%s%s\t", COLOR, $1, CLR_END
            $1=""
            n = split($0, a, "/")
            printf "%s\n", a[n]
        }
        $2 ~ /^total$/ {
            print CLR_TOTAL $0 CLR_END
        }
    '
}

main "$@"
