#!/bin/sh
window_id=$(xprop -root _NET_ACTIVE_WINDOW | cut -d\  -f5)
cpid=$(xprop -notype -id "$window_id" _NET_WM_PID | cut -d\  -f3)
sinkid=$(pactl list sink-inputs | awk -F'[#\n]' '/'$cpid'/{print $2}' RS="\n\n")

pactl set-sink-input-mute "$sinkid" toggle
