#!/bin/bash

# touchpad - Habilita/deshabilita el touchpad
# Modo de empleo: touchpad
# El nombre del dispositivo se declara como constante dentro del script.
# Errores:
#   1   Dispositivo no encontrado.
#   2   Estado parseado de la salida de "xinput list-props $DISPOSITIVO" desconocido.

#region Constantes
DEVICE="SynPS/2 Synaptics TouchPad"
DEVICE_DISABLED="0"
DEVICE_ENABLED="1"
#endregion

#region Funciones
_error() {
    if [ "$2" ]; then
        echo -e "\e[91mtouchpad: $2\e[m" >&2
    fi
    exit $1
}

_success() {
    echo -e "\e[92m$1\e[m"
}
#endregion

propiedades=`xinput list-props "$DEVICE" 2> /dev/null`
if [[ $propiedades ]]; then
    estado=`echo "$propiedades" | grep 'Device Enabled' | awk '{print $4}'`
    case $estado in
        $DEVICE_DISABLED)
            xinput enable "$DEVICE"
            _success 'Touchpad habilitado'
            ;;
        $DEVICE_ENABLED)
            xinput disable "$DEVICE"
            _success 'Touchpad deshabilitado'
            ;;
        *)
            _error 2 "estado \"$estado\" no reconocido"
    esac
else
    _error 1 "dispositivo \"$DEVICE\" no encontrado"
fi
