#!/bin/bash
# $1: URL

readonly CLR_AMAR="\e[93m"
readonly CLR_FIN="\e[m"

url=$(echo "$@" | sed "s/.*murl=//g")

url="${url//%2F//}"
url="${url//%3A/:}"
url="${url//%3D/=}"
url="${url//%3F/?}"

xdg-open "$url"
echo "Resultado:"
echo -e "${CLR_AMAR}$url${CLR_FIN}"

coupon=$(echo "$url" | grep -Po "(?<=couponCode=).*")
echo -e "Cupón: ${CLR_AMAR}$coupon${CLR_FIN}"
