#!/bin/bash

# ydl - Wrapper para Youtube-DL
# Descarga un video de YouTube(tm) y extra la pista de audio, en formato mp3.
# Modo de empleo: ydl URL NOMBRE_ARCHIVO

main() {
    declare -r url="$1"
    declare -r filename="$2"
    declare -r format="mp3"

    youtube-dl -x --audio-format "$format" "$url" -o "${filename}"'.$(ext)s'
}

main "$@"
