#!/bin/bash

# diff-sd - Comparar directorios según sus archivos.
# Se toma el primer directorio como el directorio maestro y el segundo como
# esclavo, el cual se va a tratar de terminar con el mismo contenido que el
# primer directorio.

# Si hay un archivo que está en dir1 pero no en dir2 entonces se copia del primero al otro.
# Si un archivo está en dir1 y en dir2 y son iguales entonces se ignoran.
# Si dos archivos con el mismo nombre está en dir1 y en dir2 se copia el de dir1 a dir2.
# Si hay un archivo que está en dir2 pero no en dir1 entonces se borra.

# Errores:
#   1   Se encontró un directorio desconocido en la salida de "diff".
#   2   Falló al copiar un archivo de $dir1 a $dir2.
#   3   Falló al borrar un archivo de $dir2.
#   4   No coincidió la linea con las expresiones regulares.

#region Constantes
ERASE="\e[K"
REGEX_DIST="Los ficheros binarios (.*) y .* son distintos"
REGEX_SOLO="Sólo en (.*): (.*)"
#endregion

#region Colores
CLR_ROJO="\e[91m"
CLR_VERD="\e[92m"
CLR_AMAR="\e[93m"
CLR_FIN="\e[m"
#endregion

#region Globales
solo_dir1=()
solo_dir2=()
#endregion

#region Funciones
_echo() {
    echo -e "${ERASE}${CLR_VERD}$1${CLR_FIN} $2"
}

_echo_r() {
    # Mensaje que luego va a ser sobreescrito
    echo -en "${ERASE}$1${CLR_FIN} $2\r"
}

_error() {
    if [ "$2" ]; then
        echo -e "${ERASE}${CLR_ROJO}$(basename "$0"): $2${CLR_FIN}" >&2
    fi
    exit $1
}

_mostrar_dir() {
    echo -e "${CLR_AMAR}$1${CLR_FIN}:"
}
#endregion

main() {
    dir1="$1"
    dir2="$2"

    _echo_r "Calculando diferencias"
    local diff=$(calcular_diferencias "$dir1" "$dir2")
    separar_archivos "$dir1" "$dir2" "$diff"
    copiar "$dir1" "$dir2"
    borrar "$dir2"
}

calcular_diferencias() {
    diff "$1" "$2"
}

separar_archivos() {
    local dir1="$1"
    local dir2="$2"
    local archivo
    local dir
    local linea

    IFS=$'\n'
    for linea in $3; do
        if [[ $linea =~ $REGEX_SOLO ]]; then
            dir=${BASH_REMATCH[1]}
            archivo=${BASH_REMATCH[2]}
            case $dir in
                $dir1)
                    if [[ ! -d "$dir1/$archivo" ]] ; then
                        solo_dir1+=($archivo)
                    fi ;;
                $dir2)
                    if [[ ! -d "$dir2/$archivo" ]] ; then
                        solo_dir2+=($archivo)
                    fi ;;
                *) _error 1 "directorio desconocido: $dir"
            esac
        else
            if [[ $linea =~ $REGEX_DIST ]]; then
                archivo=$(echo ${BASH_REMATCH[1]} | grep -Eo "[^/]+$")
                if [[ ! -d "$dir1/$archivo" ]] ; then
                    solo_dir1+=($archivo)
                fi
            else
                _error 4 "error de regex: $linea"
            fi
        fi
    done
}

copiar() {
    # Se copian los archivos que solo están en el primer directorio al segundo.
    local dir1="$1"
    local dir2="$2"
    local archivo

    _mostrar_dir "$dir1"
    for archivo in ${solo_dir1[@]}; do
        _echo_r "Copiando" "$archivo"
        cp -f "${dir1}/${archivo}" "${dir2}/" ||
            _error 2 "falló copiar $archivo"
        _echo "Copiado" "$archivo"
    done
}

borrar() {
    # Se borran los archivos que estén solo en el segundo directorio.
    local dir2="$1"
    local archivo

    _mostrar_dir "$dir2"
    for archivo in ${solo_dir2[@]}; do
        _echo_r "Borrando" "$archivo"
        rm "${dir2}/${archivo}" ||
            _error 3 "falló borrar $archivo"
        _echo "Borrado" "$archivo"
    done
}

main "$@"
