#!/bin/bash
if [ $EUID != 0 ]; then
    sudo "$0" "$@"
    exit $?
fi

# net - Conectarse a perfil de netctl
# Modo de empleo: net PERFIL
# Errores:
#   1   No se pasaron parámetros.
#   2   No existe el perfil.
#   3   No se pudo cambiar el perfil con "netctl switch-to $PERFIL".
#   4   No se pudo deshabilitar la interfaz con "ip set $INTERFAZ down".
#   5   No se pudo iniciar el perfil con "netctl start $PERFIL".

#region Constantes
ERASE="\e[K"
#endregion

#region Colores
CLR_ROJO="\e[91m"
CLR_VERD="\e[92m"
CLR_AMAR="\e[93m"
CLR_FIN="\e[m"
#endregion

#region echo
_echo() {
    echo -e "${ERASE}${CLR_VERD}$1 ${CLR_AMAR}$2${CLR_FIN}"
}

_echo_r() {
    # Mensaje que luego va a ser sobreescrito
    echo -en "${ERASE}$1 ${CLR_AMAR}$2${CLR_FIN}\r"
}

_error() {
    if [ "$2" ]; then
        echo -e "${ERASE}${CLR_ROJO}net: $2 ${CLR_AMAR}$3${CLR_FIN}" >&2
    fi
    exit $1
}
#endregion

main() {
    # Me fijo si hay parámetros
    if [ -z $1 ]; then
        _error 1 "falta indicar el perfil a conectarse"
    fi

    local perfil="$1" # Nombre del perfil de netctl
    existe_perfil "$perfil"

    if esta_conectado ; then
        cambiar_perfil "$perfil"
    else
        desactivar_interfaz "$perfil"
        iniciar_perfil "$perfil"
    fi

    detectar_direccion_ip
}

existe_perfil() {
    # Me fijo si existe el perfil, y salgo si no existe
    if [ ! -f "/etc/netctl/$1" ]; then
        _error 2 "no existe el perfil" "$1"
    fi
}

esta_conectado() {
    # Me fijo si ya estoy/estaba conectado a una red (debe aparecer un * al lado
    # del nombre del perfil al que estoy conectado en "netctl list".
    netctl list | grep -q "*"
}

cambiar_perfil() {
    # Si ya estaba conectado a un perfil entonces simplemente me cambio al
    # perfil nuevo.
    _echo_r "Cambiando a perfil" "$1"
    netctl switch-to "$1" 2> /dev/null ||
        _error 3 "no se pudo cambiar al perfil" "$1"
    _echo "Cambiado a perfil" "$1"
}

desactivar_interfaz() {
    # Para conectarme a un perfil si no estaba ya conectado tengo que primero
    # deshabilitar la interfaz (netctl la habilita después) e iniciar el perfil.
    local interfaz=`cat /etc/netctl/$1 |
                    grep "^Interface" |
                    grep -Eo "[^=]+$"`

    _echo_r "Desactivando la interfaz" "$interfaz"
    ip l set "$interfaz" down ||
        _error 4 "no se pudo desactivar la interfaz" "$interfaz"
    _echo "Interfaz desactivada" "$interfaz"
}

iniciar_perfil() {
    _echo_r "Iniciando perfil" "$1"
    netctl start "$1" 2> /dev/null ||
        _error 5 "no se pudo iniciar el perfil" "$1"
    _echo "Iniciado perfil" "$1"
}

detectar_direccion_ip() {
    local ip

    _echo_r "Detectando dirección IP..."
    while :; do
        ip=`ip -br -c a | \
            grep -Eo "([0-9]{1,3}[\.]){3}[0-9]{1,3}" | \
            grep -e ^192. -e ^10. -e ^168.`
        if [ "$ip" ]; then
            break
        fi
        sleep 0.1
    done
    _echo "Dirección IP:" "$ip"
}

main "$@"
