#!/bin/bash
if [ $EUID != 0 ]; then
    sudo "$0" "$@"
    exit $?
fi

# net - Conectarse a perfil de netctl
# Modo de empleo: net PERFIL
# Errores:
#   1   No se pasaron parámetros.
#   2   No existe el perfil.
#   3   No se pudo cambiar el perfil con "netctl switch-to $PERFIL".
#   4   No se pudo deshabilitar la interfaz con "ip set $INTERFAZ down".
#   5   No se pudo iniciar el perfil con "netctl start $PERFIL".

perfil="$1" # Nombre del perfil de netctl

#region Constantes
ERASE="\e[K"
#endregion

#region Colores
CLR_ROJO="\e[91m"
CLR_VERD="\e[92m"
CLR_AMAR="\e[93m"
CLR_FIN="\e[m"
#endregion

#region Funciones
_echo() {
    echo -e "${ERASE}${CLR_VERD}$1 ${CLR_AMAR}$2${CLR_FIN}"
}

_echo_r() {
    echo -en "${ERASE}$1 ${CLR_AMAR}$2${CLR_FIN}\r"
}

_error() {
    if [ "$2" ]; then
        echo -e "${ERASE}${CLR_ROJO}net: $2 ${CLR_AMAR}$3${CLR_FIN}" >&2
    fi
    exit $1
}
#endregion

# Me fijo si hay parámetros
if [ -z $1 ]; then
    _error 1 "falta indicar el perfil a conectarse"
fi

# Me fijo si existe el perfil, y salgo si no existe
if [ ! -f "/etc/netctl/$perfil" ]; then
    _error 2 "no existe el perfil" "$perfil"
fi

# Me fijo si ya estoy/estaba conectado a una red (debe aparecer un * al lado
# del nombre del perfil al que estoy conectado en "netctl list".
if netctl list | grep -q "*"; then
    # Si ya estaba conectado a un perfil entonces simplemente me cambio al
    # perfil nuevo.
    _echo_r "Cambiando a perfil" "$perfil"
    netctl switch-to "$perfil" 2> /dev/null ||
        _error 3 "no se pudo cambiar al perfil" "$perfil"
    _echo "Cambiado a perfil" "$perfil"
else
    # Para conectarme a un perfil si no estaba ya conectado tengo que primero
    # deshabilitar la interfaz (netctl la habilita después) e iniciar el perfil.
    interfaz=`cat /etc/netctl/$perfil |
                  grep "^Interface" |
                  grep -Eo "[^=]+$"`

    _echo_r "Desactivando la interfaz" "$interfaz"
    ip l set "$interfaz" down ||
        _error 4 "no se pudo desactivar la interfaz" "$interfaz"
    _echo "Interfaz desactivada" "$interfaz"

    _echo_r "Iniciando perfil" "$perfil"
    netctl start "$perfil" 2> /dev/null ||
        _error 5 "no se pudo iniciar el perfil" "$perfil"
    _echo "Iniciado perfil" "$perfil"
fi

# Muestro la dirección IP
_echo_r "Detectando dirección IP..."
while :; do
    ip=`ip -br -c a | \
            grep -Eo "([0-9]{1,3}[\.]){3}[0-9]{1,3}" | \
            grep -e ^192. -e ^10. -e ^168.`
    if [ "$ip" ]; then
        break
    fi
    sleep 0.1
done
_echo "Dirección IP:" "$ip"
